name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1- تنزيل الكود
      - name: Checkout code
        uses: actions/checkout@v3

      # 2- إعداد JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3- إعداد Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
          accept-android-sdk-licenses: true

      # 4- إعطاء صلاحية لـ gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5- بناء APK (debug)
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # 6- رفع ملف الـ APK كأرتيفاكت
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
