name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # سحب الكود من الريبو
      - name: Checkout code
        uses: actions/checkout@v4

      # تثبيت Java 17 (مطلوبة من Gradle & Android)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # تثبيت Android SDK + NDK (لأن عندك native-lib.cpp)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          ndk: 26.1.10909125
          cmake: 3.22.1

      # إعطاء صلاحية التنفيذ لملف gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # بناء APK نسخة Debug
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # رفع ملف APK كـ Artifact للتحميل
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
